set(VCPKG_ENV_PASSTHROUGH
    EMSCRIPTEN_ROOT
    EMSCRIPTEN_VERSION
    EMSDK_PYTHON
    CMAKE_NINJA_FORCE_RESPONSE_FILE)

set(EXPECTED_EMSCRIPTEN_VERSION "4.0.7")
if(NOT DEFINED ENV{EMSCRIPTEN_ROOT})
    message(FATAL_ERROR "EMSCRIPTEN_ROOT is required")
endif()
if(NOT "$ENV{EMSCRIPTEN_VERSION}" STREQUAL
       "${EXPECTED_EMSCRIPTEN_VERSION}")
    message(FATAL_ERROR
        "Expected Emscripten ${EXPECTED_EMSCRIPTEN_VERSION}, got "
        "'$ENV{EMSCRIPTEN_VERSION}'")
endif()

set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
    "${CMAKE_CURRENT_LIST_DIR}/../cmake/toolchains/vcpkg-emscripten.cmake")

set(VCPKG_C_FLAGS "-pthread -sSUPPORT_LONGJMP=wasm")
set(VCPKG_CXX_FLAGS "-pthread -fwasm-exceptions -sSUPPORT_LONGJMP=wasm")
set(VCPKG_LINKER_FLAGS "-pthread -fwasm-exceptions -sSUPPORT_LONGJMP=wasm")

list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
    "-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON")
