set(VCPKG_ENV_PASSTHROUGH
    PYTHONNOUSERSITE
    SOURCE_DATE_EPOCH)

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)
