[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu20
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True