"""Generate the target static-link-input digest embedded in the probe."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import sys
from pathlib import Path
from typing import NoReturn


FILE_ATTRIBUTE_REPARSE_POINT = 0x400
ALGORITHM = "sha256-path-null-digest-lf-v1"
MARKER_PREFIX = "RHYTHMGAME_WASM_DEPENDENCY_ARCHIVE_SUPERSET_SHA256="
WASM_OBJECT_MAGIC = b"\x00asm\x01\x00\x00\x00"


class DigestError(RuntimeError):
    pass


def _fail(message: str) -> NoReturn:
    raise DigestError(message)


def _is_reparse(entry: os.DirEntry[str]) -> bool:
    metadata = entry.stat(follow_symlinks=False)
    return entry.is_symlink() or bool(
        getattr(metadata, "st_file_attributes", 0)
        & FILE_ATTRIBUTE_REPARSE_POINT
    )


def _static_link_inputs(root: Path) -> list[Path]:
    if not root.is_dir():
        _fail(f"Installed dependency root is missing: {root}")
    root_metadata = root.lstat()
    if root.is_symlink() or bool(
        getattr(root_metadata, "st_file_attributes", 0)
        & FILE_ATTRIBUTE_REPARSE_POINT
    ):
        _fail(f"Installed dependency root reparse point is forbidden: {root}")
    result: list[Path] = []
    pending = [root]
    while pending:
        directory = pending.pop()
        with os.scandir(directory) as entries:
            for entry in entries:
                path = Path(entry.path)
                if _is_reparse(entry):
                    _fail(f"Installed dependency reparse point is forbidden: {path}")
                metadata = entry.stat(follow_symlinks=False)
                if stat.S_ISDIR(metadata.st_mode):
                    pending.append(path)
                elif stat.S_ISREG(metadata.st_mode):
                    if path.suffix in {".a", ".o"}:
                        result.append(path)
                else:
                    _fail(
                        "Installed dependency special filesystem entry is "
                        f"forbidden: {path}"
                    )
    result.sort(key=lambda value: (value.relative_to(root).as_posix().casefold(),
                                   value.relative_to(root).as_posix()))
    seen: set[str] = set()
    for path in result:
        key = path.relative_to(root).as_posix().casefold()
        if key in seen:
            _fail(
                "Duplicate installed static-link-input path under "
                f"case-folding: {path}"
            )
        seen.add(key)
    if not result:
        _fail(
            "Installed dependency root contains no static link inputs: "
            f"{root}"
        )
    return result


def _write_if_changed(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_bytes() == content:
        return
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(content)
    os.replace(temporary, path)


def generate(installed_root: Path) -> dict[str, object]:
    root = installed_root.absolute()
    files: list[dict[str, object]] = []
    aggregate = hashlib.sha256()
    inventory = hashlib.sha256()
    total_bytes = 0
    for link_input in _static_link_inputs(root):
        relative = link_input.relative_to(root).as_posix()
        content = link_input.read_bytes()
        if link_input.suffix == ".a":
            if content.startswith(b"!<thin>\n"):
                _fail(f"Thin static archive is forbidden: {relative}")
            if not content.startswith(b"!<arch>\n"):
                _fail(f"Static archive magic is invalid: {relative}")
            kind = "archive"
        else:
            if not content.startswith(WASM_OBJECT_MAGIC):
                _fail(f"Wasm object magic/version is invalid: {relative}")
            kind = "wasm-object"
        digest = hashlib.sha256(content).hexdigest()
        size = len(content)
        inventory.update(f"{relative}\n".encode("utf-8"))
        aggregate.update(f"{relative}\0{digest}\n".encode("utf-8"))
        total_bytes += size
        files.append(
            {
                "path": relative,
                "kind": kind,
                "bytes": size,
                "sha256": digest,
            }
        )
    return {
        "schemaVersion": 2,
        "algorithm": ALGORITHM,
        "fileCount": len(files),
        "totalBytes": total_bytes,
        "inventorySha256": inventory.hexdigest(),
        "aggregateSha256": aggregate.hexdigest(),
        "files": files,
    }


def _cpp(payload: dict[str, object]) -> bytes:
    marker = MARKER_PREFIX + str(payload["aggregateSha256"])
    return (
        "// Generated by generate_dependency_digest.py; do not edit.\n"
        f'namespace {{ constexpr char dependencyArchiveMarker[] = "{marker}"; }}\n'
        'extern "C" const char* rhythmGameWasmProbeDependencyArchiveMarker()\n'
        "{\n"
        "    return dependencyArchiveMarker;\n"
        "}\n"
    ).encode("utf-8")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract", type=Path, required=True)
    parser.add_argument("--installed-root", type=Path, required=True)
    parser.add_argument("--output-cpp", type=Path, required=True)
    parser.add_argument("--output-manifest", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    contract = json.loads(arguments.contract.read_text("utf-8"))
    expected_contract = {
        "schemaVersion": 2,
        "algorithm": ALGORITHM,
        "archiveSuffix": ".a",
        "wasmObjectSuffix": ".o",
        "markerPrefix": MARKER_PREFIX,
        "targetTriplet": "wasm32-emscripten-rg",
    }
    if contract != expected_contract:
        raise DigestError("Dependency archive contract drifted")
    payload = generate(arguments.installed_root)
    _write_if_changed(
        arguments.output_manifest,
        (
            json.dumps(payload, indent=2, sort_keys=True)
            + "\n"
        ).encode("utf-8"),
    )
    _write_if_changed(arguments.output_cpp, _cpp(payload))
    print(str(payload["aggregateSha256"]))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except DigestError as error:
        print(str(error), file=sys.stderr)
        raise SystemExit(2)
