if(NOT _RHYTHMGAME_VCPKG_EMSCRIPTEN_TOOLCHAIN)
    set(_RHYTHMGAME_VCPKG_EMSCRIPTEN_TOOLCHAIN 1)

    list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
        VCPKG_CRT_LINKAGE
        VCPKG_TARGET_ARCHITECTURE
        VCPKG_C_FLAGS
        VCPKG_CXX_FLAGS
        VCPKG_C_FLAGS_DEBUG
        VCPKG_CXX_FLAGS_DEBUG
        VCPKG_C_FLAGS_RELEASE
        VCPKG_CXX_FLAGS_RELEASE
        VCPKG_LINKER_FLAGS
        VCPKG_LINKER_FLAGS_RELEASE
        VCPKG_LINKER_FLAGS_DEBUG
    )

    if(NOT DEFINED ENV{EMSCRIPTEN_ROOT})
        message(FATAL_ERROR "EMSCRIPTEN_ROOT must name the pinned 4.0.7 tree")
    endif()
    set(EMSCRIPTEN_ROOT "$ENV{EMSCRIPTEN_ROOT}")
    set(_emscripten_toolchain
        "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")
    if(NOT EXISTS "${_emscripten_toolchain}")
        message(FATAL_ERROR
            "Pinned Emscripten toolchain not found: ${_emscripten_toolchain}")
    endif()

    include("${_emscripten_toolchain}")

    string(APPEND CMAKE_C_FLAGS_INIT " ${VCPKG_C_FLAGS} ")
    string(APPEND CMAKE_CXX_FLAGS_INIT " ${VCPKG_CXX_FLAGS} ")
    string(APPEND CMAKE_C_FLAGS_DEBUG_INIT " ${VCPKG_C_FLAGS_DEBUG} ")
    string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " ${VCPKG_CXX_FLAGS_DEBUG} ")
    string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " ${VCPKG_C_FLAGS_RELEASE} ")
    string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT
        " ${VCPKG_CXX_FLAGS_RELEASE} ")

    string(APPEND CMAKE_MODULE_LINKER_FLAGS_INIT
        " ${VCPKG_LINKER_FLAGS} ")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT
        " ${VCPKG_LINKER_FLAGS} ")
    string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${VCPKG_LINKER_FLAGS} ")
    string(APPEND CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT
        " ${VCPKG_LINKER_FLAGS_DEBUG} ")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT
        " ${VCPKG_LINKER_FLAGS_DEBUG} ")
    string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT
        " ${VCPKG_LINKER_FLAGS_DEBUG} ")
    string(APPEND CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT
        " ${VCPKG_LINKER_FLAGS_RELEASE} ")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT
        " ${VCPKG_LINKER_FLAGS_RELEASE} ")
    string(APPEND CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT
        " ${VCPKG_LINKER_FLAGS_RELEASE} ")
endif()
